language: python
sudo: false
env:
  matrix:
  - NUMPY_VERSION="1.7.1"
  - NUMPY_VERSION="1.9.1"
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
      pip install unittest2;
    fi
  - pip install "numpy==$NUMPY_VERSION"
install:
  - python setup.py install
script:
  - python setup.py test
  - python -m doctest README.rst
notifications:
  email: false
